### ISSUE TITLE
Discards not working

### ISSUE THREAD

**Issue by c0d3z3r0** [dm-vdo/kvdo#12]
OS: Debian 9
Kernel: 4.17.0-0.bpo.1-amd64
VDO: 6.2.0.187

Test Setup 1 (no VDO): disks->ZFS->ZVOL->ext4
Steps:
- create ext4 on VDO, mount with discard option
- zfs list shows **~0G** referenced
- create 2G file
- zfs list shows **~2.1G** referenced
- delete 2G file
- zfs list shows **~0G** referenced
*This is expected behavior.*

Test Setup 2 (with VDO): disks->ZFS->ZVOL->VDO->ext4
Steps:
- create ext4 on VDO, mount with discard option
- zfs list shows **~0G** referenced
- create 2G file
- zfs list shows **~2.1G** referenced
- delete 2G file
- zfs list shows **unchanged ~2.1G** referenced

**Looks like discard did not work. Let's discard manually:**

- fstrim on ext4
- zfs list shows **unchanged ~2.1G** referenced
- unmount ext4
- blkdiscard on vdo
- zfs list shows **unchanged ~2.1G** referenced

One more thing I noticed is that blkdiscard takes just about 10 seconds directly on zvol but minutes on VDO.

**Comment by corwin** [comment]
VDO does not issue discards to its underlying storage, and we have no plans to change this. Furthermore, VDO stacked on top of ZFS is not a supported configuration.

**Comment by brettwooldridge** [comment]
@corwin Just curious, why wouldn't VDO want to issue discards to underlying storage?  Even though compression and deduplication *reduce* write-amplification, they do no eliminate it, so isn't write-amplification (and gc) still an issue?

As IBM wrote in [Write Amplification Analysis in Flash-Based Solid State Drives](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.154.8668), *"Garbage collection is a big part of write amplification on the SSD"*.  TRIM was the industry solution to mitigate gc.  Has RedHat done enough testing to determine that VDO on SSD without discard does not suffer performance degradation over a number of months?

**Comment by corwin** [comment]
There are two reasons why VDO does not issue discards.

First, for most devices which are not at the bottom of the stack, it may be sensible to pass down discards received from above. But in the case of VDO, individual data blocks may be multiply referenced. In such a case, passing down a discard would obviously be incorrect. Furthermore, once VDO uses a block for its own metadata, VDO never gives that block up. 

So this leaves the question, is there any time at which it does make sense for VDO to choose to issue a discard? The only instance where that might make sense is when a data block becomes unreferenced. However, VDO's internal block allocator works very hard to reuse blocks which recently became unreferenced instead of allocating new blocks which have never been used before. It is also important to note that due to the nature of deduplicated storage, there is no guarantee that discarding contiguous ranges of VDOs logical blocks will result in a contiguous range of unreferenced blocks. Therefore, in general, if there are blocks whose reference counts go to 0, those blocks tend to be randomly distributed.

It is our belief (and our testing has supported this belief), that overwriting random blocks is just as good as trimming them would be in terms of SSD garbage collection, and better in terms of overall performance since a trim followed by a write is clearly less efficient than just doing a write. This is the primary reason why VDO does not issue discards to devices below it.

The second reason we don't issue discards is historical. When we first started building VDO, the kernel's interface for issuing discards (or at least the only interface which was available to us as a non-GPLed module), was synchronous. And in many cases, issuing even a single discard to certain SSDs would not only take up to 30 seconds to complete, but no other I/O would occur during that time. This was not acceptable to any of our users. Since that time, both the kernel and SSDs have improved, however, VDO's block allocator does have a way to handle blocks which are unreferenced but can't immediately be reused because they are being discarded. It would be a large amount of work to rewrite the allocator to handle blocks out for discard. Given that overwriting those blocks rather than trimming them seems to be sufficient, it has never seemed worth the investment of resources to do that work.

Finally, I'll note that most of the cases where this question comes up are not about SSDs, but rather in scenarios where VDO is stacked on top of some other thinly provisioned storage. Such scenarios were not among the use cases we considered when designing VDO and so we have not chosen to invest resources in making those scenarios work. If there is sufficient demand for such use cases, we will certainly revisit the question.
