### ISSUE TITLE
So why isn't this in the kernel?

### ISSUE THREAD

**Issue by ethancedwards8** [dm-vdo/kvdo#34]
Why isn't this in the Linux kernel?

**Comment by jwieleRH** [comment]
kvdo was originally developed by Permabit Technology Corp. as a proprietary out of tree module. After Permabit was acquired by Red Hat, kvdo was re-licensed under GPL2 and made available here. We are working very hard and making good progress to bring the source into conformance with kernel standards with respect to coding style, interfaces, and idioms so that kvdo can be accepted as an internal kernel module. For example, as a GPL licensed open source module, kvdo can use GPL licensed features that are off limits to proprietary modules. See the README.md for more details. If you would like to contribute, you can send patches to vdo-devel@redhat.com. Thank you for your interest.

**Comment by ethancedwards8** [comment]
Okay, sure thing. I'd love to contribute this seems like a really cool project, I've sent an email to the mailing list, thanks for responding.
