### ISSUE TITLE
UDS on separate device

### ISSUE THREAD

**Issue by qxrbu** [dm-vdo/kvdo#38]
From reading the documentation, it looks like the UDS index is created on the same storage device as where the data is being stored.  The documentation doesn't show a parameter to specify a different device for the UDS index. 

Is it correct to assume that at this point the UDS index and the VDO volume have to be on the same block device?

If so, can we please add a feature request to allow one to specify a different block device for a VDO volume (or perhaps even a set of VDO volumes)? 

The use case is to have the UDS index on a SSD while the UDS volume would be on a HDD.   While this is still likely not optimal since I suspect the block layout on the HDD is likely to be more random than sequential, it seems like there should be some improvement in, at least, decreasing the head contention on the HDD as it accesses the UDS and VDO volumes during normal operations.

**Comment by corwin** [comment]
Your reading of the documentation is correct. If possible, you are likely to see much more of an improvement if you could move the VDO data to SSD and the index to HDD as the index is not in the main data path and highly optimized to have a more sequential access pattern than the VDO volume itself can achieve.

In the meantime, it is certainly possible to combine some SSD and some HDD storage into a combined LVM linear device and put the VDO device on top of that in order to achieve the separation you are looking for.

In the longer term, this is likely something we will support. At the moment, we are working on deprecating and moving VDO's own python based management tools in favor of LVM. Once that work is complete, we'll be looking at ways to do things like what you are suggesting.
