### ISSUE TITLE
Question: main differences between kvdo versions 8.x and 6.x

### ISSUE THREAD

**Issue by khristenkovladimir** [dm-vdo/kvdo#71]
Hi there, 
Could you please clarify the main differences between kvdo versions 8.x and 6.x?

Thank you in advance.

**Comment by lorelei-sakai** [comment]
The largest functional difference between kvdo 6.x and kvdo 8.x is that the the latter only supports creating and managing VDO devices through LVM, and removed support for managing VDO devices with the older python tools. kvdo 8.x has a lot of structural changes related to our efforts to get VDO accepted into the linux kernel, but those should preserve existing functionality.

(In a very specific sense, because our development is mostly RHEL-focused, kvdo 6.x are the versions of kvdo included with the RHEL8 releases, while kvdo 8.x are the versions included with RHEL 9 releases. This is why most functional changes in kvdo 8.x releases get backported to 6.x releases also.)

Let us know if there are specific differences you have questions about.

**Comment by khristenkovladimir** [comment]
@lorelei-sakai this information is more than enough.
Thank you.
