### ISSUE TITLE
Is UDS no longer supported?

### ISSUE THREAD

**Issue by sm2x** [dm-vdo/kvdo#80]
Environment:
    Ubuntu 22.04.4 (5.15.0-97-generic)
    LVM version: 2.03.11-2.1ubuntu4
    VDO version: 8.2.2.2
    KVDO version: 8.2.3.3

Pardon my ignorance completely new on kvdo, is UDS dropped from the above version?
now only show depends: dm-bufio, lz4_compress

**Comment by lorelei-sakai** [comment]
This is the result of some internal architectural changes to kvdo. All of the UDS code still exists and is supported.

In the kvdo 6.x version, you can see there are two top-level directories, vdo and uds. These compiled into two separate kernel modules, with the kvdo module dependent on the uds module. However, this seemed like an unnecessary complication, so in the 8.x version, all of the code has been combined into the vdo directory, and kvdo now compiles a single kvdo module containing all the code. As a result, the uds module is no longer shown as a dependency because it no longer exists.

**Comment by sm2x** [comment]
thanks for the clarification, closing this now
